version: '3.8'

services:
  # Frontend сервис (продакшен)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studkemp-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - studkemp-network
    environment:
      - NODE_ENV=production

  # Сервис для разработки
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: studkemp-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - studkemp-network
    profiles:
      - dev

# Определение сетей
networks:
  studkemp-network:
    driver: bridge
    name: studkemp-network

# Определение томов
volumes:
  frontend_node_modules:
    name: studkemp_frontend_node_modules 